[package]
name = "bicerin-types"
version = "0.1.0"
edition = "2021"

[dependencies]
ruma = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
